### ISSUE TITLE
Change accent color to something else

### ISSUE THREAD

**Issue by PopeRigby** [dracula/steam#1]
I don't think the pink color looks very good. Maybe cyan would be better?

**Comment by Trollwut** [comment]
That would look like [this](https://i.imgur.com/KjJraIr.png) - not bad either!

I looked at the GTK theme `Ant-Dracula` in terms of color, so it fits to that. Others colors are fine, too. For me, pink is more fitting, as I also use the mentioend GTK theme.

**Comment by PopeRigby** [comment]
Could you make an alt that has cyan? If it's easy, I could do it myself and submit a PR

**Comment by Trollwut** [comment]
Yo mate!

I made a new branch here: https://github.com/dracula/steam/tree/more-colors

Could you test that for me? You should see that there is a new folder `Dracula-Cyan` in the git repo. I changed the folder structure a bit, so be sure to put `Dracula-Cyan` into your Steam's skin folder. Then after a Steam restart, you can select the skin.

If this works, I'd do that for the other colors in the colorscheme, too :)

And sure, if you have any additions to it, don't hesitate to do PRs! If possible, add screenshots of changes, because editing/restarting/selecting skins in Steam is stressful work :D

**Comment by Trollwut** [comment]
I also added the remaining colors now, too.

You can see a preview in every folder at their `thumb.png`. If you can check them for me, too, that would be nice!

If the new additions seem to be ok, I'll open a merge request for further discussions :)

E.g. things that also need to be done:

- think about how to show off all colors
- rewrite installation instructions (especially if installed via git)

**Comment by PopeRigby** [comment]
![Screenshot (32)](https://user-images.githubusercontent.com/20866468/57663694-e1d0ef80-75a9-11e9-8928-ce2a03560eff.png) Seems to be broken

**Comment by Trollwut** [comment]
Can you retest with Dracula-Pink (and another color), just to be sure it's from the recent changes?

Sorry, I'm currently not often on my main machine, which has Steam on it.

**Comment by PopeRigby** [comment]
It happens with pink...
![Screenshot (33)](https://user-images.githubusercontent.com/20866468/57742158-deef0100-7674-11e9-8b8d-75e276698466.png)
...and red too
![Screenshot (34)](https://user-images.githubusercontent.com/20866468/57742213-19f13480-7675-11e9-97a3-0849b116bd86.png)

**Comment by Trollwut** [comment]
Sorry for the late answer!

Definitely could reproduce this problem. Does not happen with the default skin. I guess with some updates, element positioning has been changed.

TBH I don't know when I come to changing this. Maybe tomorrow, if not, maybe weekend.

**Comment by Trollwut** [comment]
I finally fixed the theme for the new Steam Library. More to that in this issue: https://github.com/dracula/steam/issues/7

Just for information, the other colors (mentioned in this issue) have not been fixed yet. I might do that in time, help is also appreciated :)
