### ISSUE TITLE
Need Friend chat theme too 

### ISSUE THREAD

**Issue by Pyyaa** [dracula/steam#18]
The Steam theme is not the same as the Friend Chat theme, and that makes Steam looks kind of ugly

**Comment by tintinmaster** [comment]
Unfortunately, this is not possible.
The new friend chat is just an browser window. (You can use the chat also on your [Browser](https://steamcommunity.com/chat/))
The problem is, that this browser windows gets it .css files from the internet and not from a local file. Therefore we can not change it.
